### ISSUE TITLE
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.

### ISSUE THREAD

**Issue by rogue780** [reactphp/react#323] opened 2015-03-04 20:37 UTC

**Comment by cboden** [comment] 2015-03-06 14:56
We'll get to this probably when PSR-7 drops. In the mean time composer is simply issuing a warning. Everything still works as intended.

**Comment by clue** [comment] 2016-05-03 10:21
Afaict this has been resolved in the meantime and can be closed :+1:

**Closed by clue** 2016-05-03 10:21 UTC
