### ISSUE TITLE
Return objects from child processes instead of string STDOUT

### ISSUE THREAD

**Issue by Isty001** [reactphp/react#335] opened 2015-08-16 11:35 UTC
I'm working on a simple Twitter client, and I need process the incoming data from the Streaming api. I have a simple process which gets all the STDClasses from Twitter, to get these classes I need to dump them, and get the STDOut, but that will return a string.

Is it possible to somehow get the original objects, instead of strings?

**Comment by clue** [comment] 2016-05-03 10:11
I'm not sure I follow you :) What kind of "original objects" are you expecting here? If you're accessing a streaming HTTP API, it's expected behavior to receive the raw body contents as string chunks, as interpretation of this is entirely up the the consumer of this stream.

Considering your stream consists of JSON string(s), then you may pass this stream into a JSON decoder so that it returns individual JSON objects. Depending on what stream looks like, the following *may* help you: https://github.com/clue/php-json-stream

**Comment by clue** [comment] 2016-07-06 09:16
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2016-07-06 09:16 UTC
Labels: question
