### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by shibdib** [reactphp/react#357] opened 2016-09-17 05:51 UTC
`[2016-09-17 00:40:06] Dramiel.ERROR: exception 'ErrorException' with message 'fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:140D00CF:SSL routines:SSL_write:protocol is shutdown' in /home/Dramiel/mamba/vendor/react/stream/src/Buffer.php:86 Stack trace: #0 [internal function]: React\Stream\Buffer->handleWrite(Resource id #177, Object(React\EventLoop\StreamSelectLoop)) #1 /home/Dramiel/mamba/vendor/react/event-loop/src/StreamSelectLoop.php(240): call_user_func(Array, Resource id #177, Object(React\EventLoop\StreamSelectLoop)) #2 /home/Dramiel/mamba/vendor/react/event-loop/src/StreamSelectLoop.php(201): React\EventLoop\StreamSelectLoop->waitForStreamActivity(4862327.0988464) #3 /home/Dramiel/mamba/vendor/team-reflex/discord-php/src/Discord/Discord.php(1223): React\EventLoop\StreamSelectLoop->run() #4 /home/Dramiel/mamba/Dramiel.php(211): Discord\Discord->run() #5 {main} [] []`

This is a Discord bot (https://github.com/shibdib/Dramiel) using DiscordPHP (https://github.com/teamreflex/DiscordPHP).

This is a common problem amongst everyone using the framework.

**Comment by clue** [comment] 2016-09-17 14:31
Thanks for posting, this looks like a duplicate of your other issue at https://github.com/reactphp/stream/issues/57, so let's address this there :+1:

**Closed by clue** 2016-09-17 14:31 UTC
